name: 'Review Request Action'
description: 'Send review requests to users & teams'
author: 'Kunihiko Tanaka'
branding:
  icon: 'check'
  color: 'red'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  reviewers:
    description: 'user names csv'
    required: false
  team-reviewers:
    description: 'team names csv'
    required: false

runs:
  using: 'node18'
  main: 'lib/main.js'
